# Generated by Django 5.1.6 on 2025-03-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockdata',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddIndex(
            model_name='stockdata',
            index=models.Index(fields=['ticker', '-date'], name='myapp_stock_ticker_3f3ca9_idx'),
        ),
    ]
